### ISSUE TITLE
From GUI unable make any changes

### ISSUE THREAD

**Issue by cc08** [Hounddd/wn-blocks-theme#1]
- If I delete existing blocks - the system does not notice changes and, accordingly, does not issue a request for saving.
- If I add new blocks - the system show error "The test repeater field is required."

**Comment by damsfx** [comment]
Hi,

- I think it's the normal behavior for repeater fields.
- You may have Winter Test Plugin installed; just disable it.  
This plugin add some extras fields in the `Page` model, under a `Test` tab, with validation rule :
https://github.com/wintercms/wn-test-plugin/blob/4571241c0079d838463e5982d449ab21729d5644/Plugin.php#L198
```
$widget->model->rules += [
    'test_repeater' => 'required',
];
```

**Comment by cc08** [comment]
Yes, the problem was with this plugin. Thank you.
